/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function listen(name: string, callback: (...args: any[]) => any): void
export declare function callThreadsafeFunction(callback: (...args: any[]) => any): void
export declare class Event { }
export declare class Animal {
  name: string
  kind: number
  constructor(name: string, kind: number)
  changeName(newName: string): void
}
