[package]
name = "course"
version = "0.1.0"
edition = "2024"

[[bin]]
name="debuger"
path="src/debug/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["src/trait_lib"]

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
trait_lib = {path = "src/trait_lib"}


[profile.dev]
# opt-level = 3

[profile.release]
panic = 'abort'


[features]
default = ["xxx"] # 默认开启"xxx"
xxx = [] #  仅仅声明xxx特性，无依赖


