[package]
name = "file-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "z"
lto = "thin"
strip = true
